apps/cart/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path(r'add/',CartAddView.as_view(),name='add'),#购物车添加
    path(r'update/',CartUpdateView.as_view(),name='update'),#购物车记录更新
    path(r'delete/',CartDeleteView.as_view(),name='delete'),#购物车记录删除
    path(r'',CartInfoView.as_view(),name='info'),#购物车详情页
]

apps/order/urls.py
from django.urls import path
from apps.order.views import *
urlpatterns = [
    path(r'place',OrderPlaceView.as_view(),name='place'), #提交订单页面
    path(r'commit',OrderCommiteView.as_view(),name='commit'), #订单创建
    path(r'pay',OrderPayView.as_view(),name='pay'), #订单支付
    path(r'chack',CheckPayView.as_view(),name='chack'), #订单支付状态查询
    path(r'comment/<int:id>',ConnentView.as_view(),name='comment'), #订单评论
]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path,re_path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'tinymce/',include('tinymce.urls')),#富文本编辑器
    path(r'search/', include('haystack.urls')),#全文检索框架
    path(r'user/',include(('user.urls','user') ,namespace='user')),#用户模块
    path(r'order/',include(('order.urls','order'), namespace='order')),#订单模块
    path(r'cart/',include(('cart.urls','cart'), namespace='cart')),#购物车模块
    re_path(r'^', include(('goods.urls','goods') , namespace='goods')),#商品模块
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from apps.goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin
# Create your views here.

#/cart/add
class CartAddView(View):
    '''购物车添加视图'''
    def post(self,request):
        '''
        前端使用ajax的方式访问
        '''
        user = request.user
        if not user.is_authenticated:
            #用户未登录
            return JsonResponse({'res':1,'error':'请登录'})
        #接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        #数据校验
        if not all([sku_id,count]):
            return JsonResponse({'res':2,'error':'数据不完整'})
        # 校验添加商品的数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 3, 'error': '商品数目出错'})
        #校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id = sku_id)
        except Exception as a:
            return JsonResponse({'res': 4, 'error': '商品不存在'})
        #添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        cart_count = conn.hget(cart_key,sku.id)#没有记录时返回none
        if cart_count:
            #累加数目
            count += int(cart_count)

        #校验库存
        if count >sku.stock:
            return JsonResponse({'res': 5, 'error': '商品库存不足'})

        #设置redis中的记录。没有的话新增数据，有的话则修改。
        conn.hset(cart_key,sku_id,count)
        #计算商品条目数
        total_count = conn.hlen(cart_key)
        #返回页面
        return JsonResponse({'res': 0, 'message': '添加成功','total_count':total_count})


#/cart
class CartInfoView(LoginRequiredMixin,View):
   '''购物车页面显示'''
   def get(self,request):
       '''显示购物车页面'''
       #获取登录的用户
       user = request.user
       #获取购物车内容
       conn = get_redis_connection('default')
       cart_key = 'cart_%d'%user.id
       cart_dict = conn.hgetall(cart_key)#{'商品id'：数量}

       #遍历商品的字典，获取商品的信息
       skus=[] #记录购物车中的所有商品信息
       total_count=0 # 记录总数目
       total_price=0 # 记录总价格
       for sku_id,count in cart_dict.items():
           #通过id找到商品信息
           sku = GoodsSKU.objects.get(id = sku_id)
           #计算商品的小计
           amount = sku.price * int(count)
           #动态给sku添加属性amount来记录小计的值
           sku.amount = amount
           #动态给sku添加属性count，来记录购买的数量
           sku.count=int(count)
           skus.append(sku)
           total_price += amount
           total_count += int(count)

       #组织上下文
       context = {
           'total_count':total_count,
           'total_price':total_price,
           'skus':skus
       }
       return render(request,'cart/cart.html',context)


#更新购物车信息
#采用ajax post方式,接收商品id和数量
#/cart/update
class CartUpdateView(View):
    '''购物车记录更新'''
    def post(self,request):
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 1, 'error': '请登录'})
        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 2, 'error': '数据不完整'})
        # 校验添加商品的数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 3, 'error': '商品数目出错'})
        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except Exception as a:
            return JsonResponse({'res': 4, 'error': '商品不存在'})

        # 添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 校验库存
        if count > sku.stock:
            return JsonResponse({'res': 5, 'error': '商品库存不足'})
        cart_count = conn.hset(cart_key, sku.id,count)  # 没有记录时返回none

        # 设置redis中的记录。没有的话新增数据，有的话则修改。
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数
        vals = conn.hvals(cart_key)
        total = 0
        for value in vals:
            total += int(value)
        print(total)
        # 返回页面
        return JsonResponse({'res': 0, 'message': '更新成功','total':total})


#购物车记录删除
#采用ajax post请求，接收skuid
#/cart/delete
class CartDeleteView(View):
    '''购物车信息删除视图'''
    def post(self,request):
        '''删除购物车记录'''
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 1, 'error': '请登录'})
        #接收参数
        sku_id = request.POST.get('sku_id')
        # 数据校验
        if not sku_id:
            return JsonResponse({'res': 2, 'error': '数据不正确'})
        #商品是否存在
        try:
            sku = GoodsSKU.objects.get(id = sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'error': '商品不存在'})
        # 删除购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        # 删除
        conn.hdel(cart_key,sku_id)
        # 计算用户购物车中商品的总件数
        vals = conn.hvals(cart_key)
        total = 0
        for value in vals:
            total += int(value)
        #返回应答
        return JsonResponse({'res': 0, 'message': '删除成功','total':total})

templates/cart/cart.html
{% extends 'base_no_cart.html' %}
{% load static %}
{% block title %}天天生鲜-购物车{% endblock title %}

{% block page_title %}购物车{% endblock page_title %}

{% block body %}
	<div class="total_count">全部商品<em>{{ total_count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="{% url 'order:place' %}" method="post">
    {% for sku in skus %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="sku_ids" value="{{ sku.id }}" name="" checked></li>
		<li class="col02"><img src="{{ sku.image.url }}"></li>
		<li class="col03">{{ sku.name }}<br><em>{{ sku.price }}元/{{ sku.unite }}</em></li>
		<li class="col04">{{ sku.unite }}</li>
		<li class="col05">{{ sku.price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" sku_id="{{ sku.id }}" class="num_show fl" value="{{ sku.count }}">
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">{{ sku.amount }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}

	<ul class="settlements">
        {% csrf_token %}
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
    </form>
{% endblock body %}
{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
    //计算被选中的商品的总件数和总价格
    //获取所有被选中的商品，并获取父级的ul元素
    function update_page_info (){
        total_count=0
        total_price=0
        $('.cart_list_td').find(':checked').parents('ul').each(function () {
            count = $(this).find('.num_show').val()//数量
            amount = $(this).children('.col07').text()//小计
            //累加计算商品的总件数和总价格
            total_count += parseInt(count)
            total_price += parseFloat(amount)
        })
        //设置被选中商品的总件数和总价格
        $('.settlements').find('em').text(total_price.toFixed(2))
        $('.settlements').find('b').text(total_count)

    }


    //计算商品小计
    function update_goods_amount(sku_ul){
        //获取商品的价格和数量进行计算
        count = $(sku_ul).find('.num_show').val()//数量
        price = $(sku_ul).children('.col05').text()//价格
        //计算小计
        amount = parseInt(count) * parseFloat(price)
        //设置小计
        sku_ul.children('.col07').text(amount.toFixed(2)+'元')
    }


    //商品列表全选与全不选
    $('.settlements').find(':checkbox').change(function () {
        //获取全选的状态
        is_checked = $(this).prop('checked')
        //遍历商品对应的checkbox,设置这些checkbox的选中状态与全选的checkbox状态一致。
        $('.cart_list_td').find(':checkbox').each(function () {
            $(this).prop('checked',is_checked)
        })
        //更新页面信息
        update_page_info()
    })


    //商品对应的chacbox状态发送改变时，设置全选checkbox的状态
    $('.cart_list_td').find(':checkbox').change(function () {
        //获取页面上商品的数目
        all_len = $('.cart_list_td').length
        //获取页面被选中商品的数目
        check = $('.cart_list_td').find(':checked').length
        is_checked = true
        if (all_len != check){
            is_checked=false
        }
        $('.settlements').find(':checkbox').prop('checked',is_checked)
        update_page_info()
    })


    error_update = true
    total=0
    //更新购物车中商品的属性
    function update_remote_cart_info(sku_id,count){
        csrf_token = $('input[name="csrfmiddlewaretoken"]').val()
        //组织参数
        params = {
            'sku_id':sku_id,
            'count':count,
            'csrfmiddlewaretoken':csrf_token
        }

        //ajax默认是异步执行，肯能会导致没有接收到数据就执行之后的操作。
        //ajax关闭异步,会影响全局，在这个请求完成后再打开异步
        $.ajaxSettings.async = false
        $.post('/cart/update/',params,function (date) {
            if(date.res == 0){
                error_update= false
                total=date.total
            }else {
                //更新失败
                alert(date.error)
                error_update = true
            }
        })
        //ajax开启异步
        $.ajaxSettings.async = true

    }


    //购物车商品数量增加
    $('.add').click(function () {
        // 获取商品id和数量
        count = $(this).next().val()
        sku_id = $(this).next().attr('sku_id')
        csrf_token = $('input[name="csrfmiddlewaretoken"]').val()
        //组织参数
        count = parseInt(count)+1
        //调用购物车更新方法
        update_remote_cart_info(sku_id,count)
        //判断更新是否成功
        console.log(error_update)
        if(error_update == false){
            //重新设置商品的数目
            $(this).next().val(count)
            //计算商品小计
            update_goods_amount($(this).parents('ul'))
            //获取商品对应的checkbox的选中状态，如果被选中则跟新页面信息
            is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
            console.log(is_checked)
            if (is_checked){
                //被选中则更新页面信息
                update_page_info()
            }
            //更新页面上购物车商品的总件数
            $('.total_count').children('em').text(total)

        }
    })


    //购物车商品减少
    $('.minus').click(function () {
        // 获取商品id和数量
        count = $(this).prev().val()
        sku_id = $(this).prev().attr('sku_id')
        count = parseInt(count) - 1
        //校验参数
        if (count <=0){
            count = 1
        }
        //调用购物车内容更新方法
        update_remote_cart_info(sku_id,count)
        //判断更新是否成功
        console.log(error_update)
        if(error_update == false){
            //重新设置商品的数目
            $(this).prev().val(count)
            //计算商品小计
            update_goods_amount($(this).parents('ul'))
            //获取商品对应的checkbox的选中状态，如果被选中则跟新页面信息
            is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
            console.log(is_checked)
            if (is_checked){
                //被选中则更新页面信息
                update_page_info()
            }
            //更新页面上购物车商品的总件数
            $('.total_count').children('em').text(total)

        }
    })


    //记录手动修改前的商品数量
    pre_count = 0
    $('.num_show').focus(function () {
        pre_count = $(this).val()
    })

    //购物车商品数量手动输入
    $('.num_show').blur(function () {
        // 获取商品id和数量
        count = $(this).val()
        sku_id = $(this).attr('sku_id')
        //校验参数
        if(isNaN(count) || count.trim().length==0 || parseInt(count) <=0){
            //当修改的数值不正确时，改回原来的值
            $(this).val(pre_count)
            return
        }

        //调用购物车内容更新方法
        count = parseInt(count)
        update_remote_cart_info(sku_id,count)
        //判断更新是否成功
        console.log(error_update)
        if(error_update == false){
            //重新设置商品的数目
            $(this).val(count)
            //计算商品小计
            update_goods_amount($(this).parents('ul'))
            //获取商品对应的checkbox的选中状态，如果被选中则跟新页面信息
            is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
            console.log(is_checked)
            if (is_checked){
                //被选中则更新页面信息
                update_page_info()
            }
            //更新页面上购物车商品的总件数
            $('.total_count').children('em').text(total)

        }else {
            //当修改的数值失败时，改回原来的值
            $(this).val(pre_count)
        }
    })

    //购物车记录删除
    $('.cart_list_td').children('.col08').children('a').click(function () {
        //获取商品id
        sku_id = $(this).parents('ul').find('.num_show').attr('sku_id')
        csrf_token = $('input[name="csrfmiddlewaretoken"]').val()
        //组织参数
        params = {
            'sku_id':sku_id,
            'csrfmiddlewaretoken':csrf_token
        }

        //获取商品所在的ul元素
        sku_ul = $(this).parents('ul')
        //ajax默认是异步执行，肯能会导致没有接收到数据就执行之后的操作。
        //ajax关闭异步,会影响全局，在这个请求完成后再打开异步
        $.ajaxSettings.async = false
        $.post('/cart/delete/',params,function (date) {
            if(date.res == 0){
                //删除成功
                //获取sku_ul中商品的选中状态
                is_checked = sku_ul.find(':checkbox').prop('checked')
                //移除页面上的商品所在的ul元素
                sku_ul.remove()//删除自身及子元素
                if(is_checked){
                    //如果是选中状态，更新结算
                    update_page_info()
                }
                //更新页面上购物车商品的总件数
                $('.total_count').children('em').text(date.total)

            }else {
                //删除失败
                alert(date.error)
            }
        })
        //ajax开启异步
        $.ajaxSettings.async = true

    })
    </script>
{% endblock bottomfiles %}