apps/cart/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path(r'add/',CartAddView.as_view(),name='add'),#购物车添加
    path(r'update/',CartUpdateView.as_view(),name='update'),#购物车记录更新
    path(r'delete/',CartDeleteView.as_view(),name='delete'),#购物车记录删除
    path(r'',CartInfoView.as_view(),name='info'),#购物车详情页
]

apps/goods/urls.py
from django.urls import path
from apps.goods import views
urlpatterns = [
    path(r'index/',views.IndexView.as_view(),name = 'index'),
    path(r'detail/<int:sku_id>/',views.DateilView.as_view(),name='detail'),
    path(r'list/<int:type_id>/<int:page>/',views.ListView.as_view(),name='list')

]

apps/user/urls.py
from django.urls import path
from apps.user.views import *
#内置的登录状态判断 装饰器
from django.contrib.auth.decorators import login_required
urlpatterns = [
    path('register/',RegisterView.as_view(),name='register'), #指向 用户注册 类视图处理方法
    path('login/',LoginView.as_view(),name='login'), #指向 用户登陆 类视图处理方法
    path('action/<str:token>',ActiveView.as_view(),name='active'), #指向 用户激活 类视图处理方法

    path('logout',LogoutView.as_view(),name='logout'),# 退出系统
    #path('address/',login_required(UserAddressView.as_view()),name='address'),# 用户中心地址页
    #path('order/',login_required(UserOrderView.as_view()),name='order'),# 用户中心订单页
    #path('',login_required(UserInfoView.as_view()),name='user')# 用户中心信息页

    path('address/',UserAddressView.as_view(),name='address'),# 用户中心地址页
    path('order/<int:page>',UserOrderView.as_view(),name='order'),# 用户中心订单页
    path('',UserInfoView.as_view(),name='user')# 用户中心信息页
]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path,re_path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'tinymce/',include('tinymce.urls')),#富文本编辑器
    path(r'search/', include('haystack.urls')),#全文检索框架
    path(r'user/',include(('user.urls','user') ,namespace='user')),#用户模块
    path(r'order/',include(('order.urls','order'), namespace='order')),#订单模块
    path(r'cart/',include(('cart.urls','cart'), namespace='cart')),#购物车模块
    re_path(r'^', include(('goods.urls','goods') , namespace='goods')),#商品模块
]

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block topfile %}{% endblock topfile %}

</head>
<body>
{# 网页顶部 #}
{% block header_con %}
        <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出登录</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:info' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_con %}
{# 网页顶部搜索框 #}
{% block search_bar %}
    	<div class="search_bar clearfix">
		<a href="/index" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<form method="get" action="/search">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
			</form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:info' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}
{# 主体内容 #}
{% block body %}{% endblock body %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

{# 底部html元素 #}
{% block bottom %}{% endblock bottom%}
{# 底部文件导入 #}
{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1%}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor%}

				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index'%}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页、列表页 主体内容 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_no_cart.html
{# 购物车 提交订单 #}
{% extends 'base.html' %}
{% load static %}
{# 网页顶部搜索框无购物车 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index'%}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar %}

templates/base_user_center.html
{# 用户中心的三个页面 #}
{% extends 'base_no_cart.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href="{% url 'user:user' %}"{% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
            <li><a href="{% url 'user:order' 1 %}"{% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
            <li><a href="{% url 'user:address' %}"{% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
        </ul>
    </div>

{# 用户中心右侧内容 #}
{% block right_conten %}{% endblock right_conten %}
</div>
{% endblock body %}

templates/delindex.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfile %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfile %}
{% block body %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
                <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners  %}
				    <li><a href="#"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				    <a href="#">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="#">{{ banner.sku.name }}</a></h4>
					<a href="#"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}
{% block bottomfiles %}
    <script type="text/javascript" src="js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock bottomfiles %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfile %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfile %}
{% block body %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
                <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners  %}
				    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				    <a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1%}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="#">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜-登录{% endblock title %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="login_top clearfix">
		<a href="/index" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register">立即注册</a>
				</div>
				<div class="form_input">
                    {# 不设置表单action时，提交表单时，会向浏览器地址栏中的地址提交数据 #}
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
    {{ errmsg }}
{% endblock body %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜-注册{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="/user/register/">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
                {{ errmsg }}
			</div>
		</div>
	</div>
{% endblock body %}