apps/goods/urls.py
from django.urls import path
from apps.goods import views
urlpatterns = [
    path(r'index/',views.IndexView.as_view(),name = 'index'),
    path(r'detail/<int:sku_id>/',views.DateilView.as_view(),name='detail'),
    path(r'list/<int:type_id>/<int:page>/',views.ListView.as_view(),name='list')

]

apps/user/urls.py
from django.urls import path
from apps.user.views import *
#内置的登录状态判断 装饰器
from django.contrib.auth.decorators import login_required
urlpatterns = [
    path('register/',RegisterView.as_view(),name='register'), #指向 用户注册 类视图处理方法
    path('login/',LoginView.as_view(),name='login'), #指向 用户登陆 类视图处理方法
    path('action/<str:token>',ActiveView.as_view(),name='active'), #指向 用户激活 类视图处理方法

    path('logout',LogoutView.as_view(),name='logout'),# 退出系统
    #path('address/',login_required(UserAddressView.as_view()),name='address'),# 用户中心地址页
    #path('order/',login_required(UserOrderView.as_view()),name='order'),# 用户中心订单页
    #path('',login_required(UserInfoView.as_view()),name='user')# 用户中心信息页

    path('address/',UserAddressView.as_view(),name='address'),# 用户中心地址页
    path('order/<int:page>',UserOrderView.as_view(),name='order'),# 用户中心订单页
    path('',UserInfoView.as_view(),name='user')# 用户中心信息页
]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path,re_path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'tinymce/',include('tinymce.urls')),#富文本编辑器
    path(r'search/', include('haystack.urls')),#全文检索框架
    path(r'user/',include(('user.urls','user') ,namespace='user')),#用户模块
    path(r'order/',include(('order.urls','order'), namespace='order')),#订单模块
    path(r'cart/',include(('cart.urls','cart'), namespace='cart')),#购物车模块
    re_path(r'^', include(('goods.urls','goods') , namespace='goods')),#商品模块
]

apps/order/models.py
from django.db import models
from db.base_model import BaseModel
# Create your models here.


class OrderInfo(BaseModel):
    '''订单模型类'''
    PAY_METHOD = {
        '1': '货到付款',
        '2':'微信支付',
        '3':'支付宝',
        '4':'银联支付'
    }
    PAY_METHODS_ENUM={
        'CASH':1,
        "ALIPAY":2
    }
    ORDER_STATUS_ENUM={
        'UNPAID':1,
        'UNSEND':2,
        'UNRECEIVED':3,
        'UNCOMMENT':4,
        'FINISHED':5
    }
    PAY_METHOD_CHOICES = (
        (1, '货到付款'),
        (2, '微信支付'),
        (3, '支付宝'),
        (4, '银联支付')
    )

    ORDER_STATUS_CHOICES = (
        (1, '待支付'),
        (2, '待发货'),
        (3, '待收货'),
        (4, '待评价'),
        (5, '已完成')
    )

    order_id = models.CharField(max_length=128, primary_key=True, verbose_name='订单id')
    user = models.ForeignKey('user.User', verbose_name='用户',on_delete=models.PROTECT)
    addr = models.ForeignKey('user.Address', verbose_name='地址',on_delete=models.PROTECT)
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHOICES, default=3, verbose_name='支付方式')
    total_count = models.IntegerField(default=1, verbose_name='商品数量')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品总价')
    transit_price = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='订单运费')
    order_status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES, default=1, verbose_name='订单状态')
    trade_no = models.CharField(max_length=128,default="", verbose_name='支付编号')

    class Meta:
        db_table = 'df_order_info'
        verbose_name = '订单'
        verbose_name_plural = verbose_name


class OrderGoods(BaseModel):
    '''订单商品模型类'''
    order = models.ForeignKey('OrderInfo', verbose_name='订单',on_delete=models.PROTECT)
    sku = models.ForeignKey('goods.GoodsSKU', verbose_name='商品SKU',on_delete=models.PROTECT)
    count = models.IntegerField(default=1, verbose_name='商品数目')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    comment = models.CharField(max_length=256,default = "", verbose_name='评论')

    class Meta:
        db_table = 'df_order_goods'
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel
# Create your models here.

class User(AbstractUser,BaseModel):
    '''用户模型类'''

    class Meta:
        db_table = "df_user"
        verbose_name = "用户"
        verbose_name_plural  = verbose_name


class AddressManager(models.Manager):
    '''地址模型管理类'''
    # 改变原有的查询的结果集
    def all(self):
        '''获取所有没有被删除的地址信息'''
        address = self.filter(is_delete=False)
        return address
    # 封装新的方法,用于操作模型类对应的数据包

    def get_default_address(self,user):
        # self.model 获取self所在的模型类
        '''获取用户的默认收获地址'''
        try:
            address = self.get(user=user,is_default=True)
            # 加密手机号
            address.phone = address.phone.replace(address.phone[3:7], '****')
        except self.model.DoesNotExist:
            # 没有默认地址
            address = None
        return address

class Address(BaseModel):
    '''地址模型类'''
    user = models.ForeignKey('User',verbose_name='所属账户', on_delete=models.DO_NOTHING)
    receiver = models.CharField(max_length=20,verbose_name="收件人")
    addr = models.CharField(max_length=256,verbose_name='收件地址')
    zip_code = models.CharField(max_length=6,null=True,verbose_name='邮政编码')
    phone = models.CharField(max_length=11,verbose_name='联系电话')
    is_default = models.BooleanField(default=False,verbose_name='是否默认')
    # 自定义模型管理器对象
    objects = AddressManager()
    class Meta:
        db_table = "df_address"
        verbose_name = '地址'
        verbose_name_plural = verbose_name

apps/user/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import View
from apps.user.models import User,Address
from apps.goods.models import GoodsSKU
from apps.order.models import OrderInfo,OrderGoods
# 导入django内置用户认证模块
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator

from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
from dailyfresh.settings import SECRET_KEY
import re

from celery_tasks.tasks import send_register_active_email

#登录状态判断Mixin
from utils.mixin import LoginRequiredMixin

from django_redis import get_redis_connection

# Create your views here.

'''
django3 的验证系统官方文档
https://docs.djangoproject.com/zh-hans/3.1/topics/auth/default/
'''

# /user/register
class RegisterView(View):
    '''注册功能的类视图'''

    def get(self, request):
        '''显示页面'''
        return render(request, 'register.html')

    def post(self, request):
        '''进行注册处理'''
        '''注册处理方法'''
        # 接收数据
        username = request.POST.get('user_name')
        password = request.POST.get('pwd')
        cpwd = request.POST.get('cpwd')
        email = request.POST.get('email')
        allow = request.POST.get('allow')
        # 数据校验
        if allow != 'on':
            # 没有选接受协议
            return render(request, 'register.html', {'errmsg': '请同意协议'})
        if not all([username, password, email]):  # 使用all方法，给all方法中传递一个可迭代对象，如果都为真时返回 真
            # 数据不完整时
            return render(request, 'register.html', {'errmsg': '数据不完整'})
        # 校验邮箱
        if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
            # 邮箱不合法
            return render(request, 'register.html', {'errmsg': '邮箱不合法，格式不正确'})
        # 校验用户是否已存在
        try:
            User.objects.get(username=username)
            user = True  # 表示已存在
        except User.DoesNotExist as err:
            # 抛错时表示用户名不存在
            user = False  # 表示不存在
        if user:
            return render(request, 'register.html', {'errmsg': '用户已存在'})

        # 进行业务处理（进行用户注册）
        user = User.objects.create_user(username=username, password=password, email=email)
        user.is_active = 0  # 注册完成后默认不激活
        user.save()

        # 发送激活邮件，包含激活连接:http://127.0.0.1:8000/user/action/
        ## 激活连接中需要包含用户的信息，并且需要进行加密


        serializer = Serializer(SECRET_KEY, 3600)  # 一小时后失效
        dumps_user_token = {'confirm': user.id}
        dumps_user_token = serializer.dumps(dumps_user_token)
        dumps_user_token = str(dumps_user_token, encoding='utf-8')
        # 通过异步方式发送邮件
        send_register_active_email.delay(username = user.username,to_email = user.email , token=dumps_user_token)

        # 返回应答,跳转到首页
        return redirect(reverse('goods:index'))


# /user/active/123123123
class ActiveView(View):
    '''用户激活'''

    def get(self, request, token):
        '''进行用户激活'''
        # 解密
        serializer = Serializer(SECRET_KEY, 3600)  # 一小时后失效
        try:
            loads_user_token = serializer.loads(token)  # 进行解密
            # 获取解密过后的信息
            user_id = loads_user_token['confirm']

            # 通过用户id 读取数据库中的用户信息
            user = User.objects.get(id=user_id)
            user.is_active = 1
            user.save()
            # 返回应答
            # return HttpResponse('%s,恭喜您激活成功'%user.username)
            # 返回等登陆界面
            return redirect(reverse('user:login'))

        except SignatureExpired as error:
            # 激活链接无效
            return HttpResponse("激活链接无效")

# /user/login
class LoginView(View):
    '''登陆'''

    def get(self, request):
        '''显示登陆界面'''
        #判断是否记住用户名
        if 'username' in request.COOKIES:
            username = request.COOKIES.get('username')
            checked = 'checked'
        else:
            username = ""
            checked = ""
        return render(request, 'login.html',{'username':username,'checked':checked})
    def post(self,request):
        '''登录校验'''

        # 接收数据
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        # 校验身份
        if not all([username, password]):
            return render(request,'login.html',{'errmsg':'数据不完整'})

        #user = User.objects.get(username=username,password=password)
        ## 通过django内置用户认证方法进行认证
        user = authenticate(username=username,password=password)
        print(user)
        if user is not None:
            # 用户名密码正确
            if user.is_active:
                # 已激活用户
                # 记录用户的登录状态:使用django内置的登录方法，会将登录的信息保存到session中
                login(request,user)

                #获取登录页面中地址后面的next内容，默认值设为系统主页
                next_url = request.GET.get('next',reverse('goods:index'))
                # 创建一个HttpResponseRedirect对象，方便之后添加cookie信息
                response = redirect(next_url)


                # 判断 是否记住 用户名
                remember = request.POST.get('remember')
                if remember =='on':
                    # 记住用户名
                    response.set_cookie('username', username, max_age=7*24*3600)
                else:
                    response.delete_cookie('username')
                # 获取所需要跳转到地址信息
                # 返回应答
                return response
            else:
                # 未激活用户
                return render(request, 'login.html', {'errmsg': '用户未激活'})
        else:
            # 用户名或密码错误
            return render(request, 'login.html', {'errmsg': '用户名或密码错误'})

# /user/logout
class LogoutView(View):
    def get(self,request):
        '''退出用户'''
        #清楚用户的session信息
        logout(request)
        return redirect(reverse("goods:index"))


#/user
class UserInfoView(LoginRequiredMixin,View):
    '''用户信息-信息页'''
    def get(self,request):

        # 如果用户没有登录 request.user 是AnonymousUser类的一个实例,is_authenticated返回False
        # 如果用户登录 request.user 是User类的一个实例,is_authenticated返回True
        # request.user.is_authenticated()
        # 在django中除了自己设定的模板变量之外，django还会把request.user也传给模板文件（名字为user）

        # 获取用户的个人信息
        # 获取对应的user对象
        user = request.user
        address = Address.objects.get_default_address(user=user)

        # 获取用户的历史浏览记录
        # 从redis数据库中获取浏览记录
        con = get_redis_connection('default')
        history_key = 'history_%d'%user.id
        sku_ids = con.lrange(history_key,0,4)#取前五个
        print(sku_ids)
        # 获取前五个浏览记录中的商品信息
        # 遍历查询，以便保持对应的位置
        goods_li = []
        for id in sku_ids:
            goods = GoodsSKU.objects.get(id=id)
            goods_li.append(goods)

        # 组织上下问
        context= {
            'page':"user",
            'address':address,
            "goods_li":goods_li
        }
        print(goods_li)
        return render(request,'user/user_center_info.html',context)

#/user/order
class UserOrderView(LoginRequiredMixin,View):
    '''用户信息-订单页'''
    def get(self,request,page):
        # 获取用户的订单信息
        user = request.user
        orders = OrderInfo.objects.filter(user=user).order_by('-create_time')
        #遍历获取获取订单商品的信息
        for order in orders:
            order_skus = OrderGoods.objects.filter(order_id = order.order_id)
            #遍历order_skus计算商品小计
            for order_sku in order_skus:
                amount = order_sku.count*order_sku.price
                #动态给order_sku增加amount，保存订单商品的小计
                order_sku.amount = amount
            # 动态给order增加属性，保存订单商品的信息
            order.order_skus = order_skus
            order.final_price = order.total_price+order.transit_price#最终价格
            print(order.final_price)
        # 分页
        paginater = Paginator(orders,5)
        # 处理页码
        # 获取第paginater的内容
        try:
            page = int(page)
        except Exception as e:
            page = 1
        # 判断是否超出范围
        if page > paginater.num_pages:
            page = 1
        if page < 1:
            page = 1

        # 获取指定页的内容
        order_page = paginater.page(page)
        # 控制页面上最多显示五个页码
        # 1 总页数小于五页，页码显示所有页码
        # 2 当前页是前三页，显示1-5页
        # 3 当前页是后三页，显示后五页
        # 4 其他，显示当前页的前两页和后两页
        num_pages = paginater.num_pages
        if num_pages < 5:
            pages = range(1, num_pages + 1)
        elif page <= 3:
            pages = range(1, 6)
        elif num_pages - page <= 2:  # 后三页
            pages = range(num_pages - 4, num_pages + 1)
        else:
            pages = range(page - 2, page + 3)
        # 组织上下文
        context={
            'order_page':order_page,
            'pages':pages,
            'page': "order",

        }
        # 返回应答
        return render(request,'user/user_center_order.html',context)

#/user/address
class UserAddressView(LoginRequiredMixin,View):
    '''用户信息-地址页'''
    def get(self,request):
        # 获取对应的user对象
        user = request.user
        # 获取用户的默认受收获地址
        address = Address.objects.get_default_address(user=user)

        return render(request,'user/user_center_site.html',{'page':"address",'address':address})

    def post(self,request):
        '''地址添加'''
        #接受数据
        receiver = request.POST.get('reveiver')
        addr = request.POST.get('addr')
        zip_code = request.POST.get('zip_code')
        phone = request.POST.get('phone')
        #校验数据
        if not all([receiver,addr,phone]):
            return render(request,'user/user_center_site.html',{'page':"address",'errmsg':'数据不完整'})
        # 校验手机号
        if not re.match(r'^1[3|4|5|7|8][0-9]{9}$',phone):
            return render(request, 'user/user_center_site.html', {'page': "address", 'errmsg': '手机号格式错误'})

        #添加地址
        #如果用户已存在默认收获地址则添加的收货地址设为默认，否则新添加的收货地址不设为默认地址

        #获取对应的user对象
        user = request.user
        address = Address.objects.get_default_address(user=user)

        if address:
            is_default = False
        else:
            is_default = True

        # 创建地址
        Address.objects.create(user=user,
                               receiver=receiver,

templates/user/user_center_info.html
{% extends 'base_user_center.html' %}
{% block right_conten %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
                            {% if address %}
                            <li><span>联系方式：</span>{{ address.phone }}</li>
							<li><span>联系地址：</span>{{ address.addr }}</li>
                            {% else %}
                            <li><span>联系方式：</span>无</li>
							<li><span>联系地址：</span>无</li>
                            {% endif %}

						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
					{% for goods in goods_li %}
						<li>
						<a href="{% url 'goods:detail' goods.id%}"><img src="{{ goods.image.url }}"></a>
						<h4><a href="detail.html">{{ goods.name }}</a></h4>
						<div class="operate">
							<span class="prize">￥{{ goods.price }}</span>
							<span class="unit"{{ goods.price }}/{{ goods.unite }} </span>
								<a href="#" class="add_goods" title="加入购物车"></a>
							</div>
						</li>
					{% empty %}
					<h3>无历史浏览记录</h3>
					{% endfor %}
                    </ul>
                </div>
		</div>
{% endblock right_conten %}

templates/user/user_center_order.html
{% extends 'base_user_center.html' %}
{% load static %}
{% block right_conten %}
		<div class="right_content clearfix">
                {% csrf_token %}
				<h3 class="common_title2">全部订单</h3>
            {% for order in order_page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.create_time }}</li>
					<li class="col02">订单号：{{ order.order_id }}</li>
					<li class="col02 stress">{{ order.get_order_status_display }}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order_sku in order.order_skus %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{{ order_sku.sku.image.url }}"></li>
									<li class="col02">{{ order_sku.sku.name }}<em>{{ order_sku.price }}元/{{ order_sku.sku.unite }}</em></li>
									<li class="col03">{{ order_sku.count }}</li>
									<li class="col04">{{ order_sku.amount }}元</li>
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ order.final_price }}元(含运费:{{ order.transit_price }}元)</td>
							<td width="15%">{{ order.get_order_status_display }}</td>
							<td width="15%"><a href="#" order_id={{ order.order_id }} status={{ order.order_status }} class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
            {% endfor %}

				<div class="pagenation">
                    {% if order_page.has_previous_page %}
					<a href="{% url 'user:order' order_page.previous_page_number %}">上一页</a>
                    {% endif %}
                    {% for pindex in pages %}
                        {% if pindex == order_page.number %}
					        <a href="{% url 'user:order' pindex %}" class="active">{{ pindex }}</a>
                        {% else %}
                            <a href="{% url 'user:order' pindex %}">{{ pindex }}</a>
                        {% endif %}

                    {% endfor %}
                    {% if order_page.has_next_page %}
					<a href="{% url 'user:order' order_page.next_page_number %}">下一页</a>
                    {% endif %}
				</div>
		</div>

{% endblock right_conten %}
{% block bottomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
    $('.oper_btn').each(function () {
        status = $(this).attr('status')
        if(status == 1){
            $(this).text('去支付')
        }else if(status == 4){
            $(this).text('去评价')
        }else if(status == 5){
            $(this).text('已完成')
        }
    })
    $('.oper_btn').click(function () {
        status = $(this).attr('status')
        //获取订单id
        order_id = $(this).attr('order_id')
        csrf_token = $('input[name="csrfmiddlewaretoken"]').val()
        if (status ==1){
            //待支付，进行处理
            //组织参数
            params={
                'order_id':order_id,
                "csrfmiddlewaretoken":csrf_token
            }
            //发起ajax post请求，访问order/pay 传递order_id
            $.post('/order/pay',params,function (date) {
                if (date.res == 0){
                    //成功
                    //引导用户到支付页面
                    window.open(date.pay_url)
                    //浏览器访问/order/chack 获取交易结果
                    // ajax post 请求，传递order_id
                    $.post('/order/chack',params,function (date) {
                        if(date.res == 0){
                            alert('支付成功')
                            location.reload()//刷新页面
                        }
                    })
                }else{
                    //失败
                    alert(date.error)
                }
            })
        }else if(status == 4 ){
            //等待评论，跳转到评论页面
            location.href = '/order/comment/'+ order_id
        }


        else {
            //其他情况
        }

    })
    </script>
{% endblock %}

templates/user/user_center_site.html
{% extends 'base_user_center.html' %}
{% block right_conten %}
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if address %}
                            <dd>{{ address.addr }} （{{ address.receiver }} 收） {{ address.phone }}</dd>

                        {% else %}
                            <dd>没有默认地址</dd>
                        {% endif %}

					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="reveiver">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
                    {{ errmsg }}
				</div>
		</div>
{% endblock right_conten %}